# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 18:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Action', max_length=100)),
                ('method', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('ip', models.CharField(db_index=True, max_length=100)),
                ('endpoint', models.TextField(db_index=True)),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('headers', jsonfield.fields.JSONField(blank=True, null=True)),
                ('data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
